# Outdated script, no longer works.
# Changed build commands, file output. The output is now:
# .\out\rel32\SumatraPDF.exe
# .\out\rel32\SumatraPDF-dll.exe
# .\out\rel64\SumatraPDF.exe
# .\out\rel64\SumatraPDF-dll.exe

name: Alternative Build
on:
  workflow_dispatch
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          # needed to calc build number via git log --oneline
          fetch-depth: 0

#      - name: Build x86
#        run: .\doit.bat -ci
# 
#      - name: Copy files to root
#        shell: bash
#        run: |
#          cp "./out/final-prerel/SumatraPDF-prerel-32.exe" "SumatraPDF-prerel-32.exe"
#          cp "./out/final-prerel/SumatraPDF-prerel-32.zip" "SumatraPDF-prerel-32.zip"
#          cp "./out/final-prerel/SumatraPDF-prerel-32-install.exe" "SumatraPDF-prerel-32-install.exe"
#      - name: Clean out
#        shell: bash
#        run: rm -r "./out"

      - name: Build x64
        run: .\doit.bat -build-pre-rel

      - name: Copy files to root
        shell: bash
        run: |
          cp "./out/final-prerel/SumatraPDF-prerel-64.exe" "SumatraPDF-prerel-64.exe"
          cp "./out/final-prerel/SumatraPDF-prerel-64.zip" "SumatraPDF-prerel-64.zip"
          cp "./out/final-prerel/SumatraPDF-prerel-64-install.exe" "SumatraPDF-prerel-64-install.exe"
      - name: Get last commit date
        id: getdate
        shell: bash
        run: |
          get_date=$(git log --pretty=format:"%cs" -1)
          echo "last_commit_date=$get_date" >> "$GITHUB_OUTPUT"
        
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: |
#            SumatraPDF-prerel-32.exe
#            SumatraPDF-prerel-32.zip
#            SumatraPDF-prerel-32-install.exe
            SumatraPDF-prerel-64.exe
            SumatraPDF-prerel-64.zip
            SumatraPDF-prerel-64-install.exe
          tag_name: "pre.${{ steps.getdate.outputs.last_commit_date }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
